import type { SyntaxToken } from "./components/ui/syntax-typing-animation";

/**
 * Landing-page typing demo: TradeSphere Strategy Studio / dashboard script
 * syntax (price, buy, log, cash — through `if cash() > 100:`).
 */
export const mainDemoSyntaxSegments: SyntaxToken[] = [
    { text: "// Typing in your trade", className: "text-slate-500 italic" },
    { text: "\n", className: "text-slate-200" },
    { text: "if", className: "text-violet-400" },
    { text: " ", className: "text-slate-200" },
    { text: "price", className: "text-emerald-400" },
    { text: "(", className: "text-slate-400" },
    { text: '"', className: "text-slate-400" },
    { text: "NVDA", className: "text-sky-300" },
    { text: '"', className: "text-slate-400" },
    { text: ")", className: "text-slate-400" },
    { text: " ", className: "text-slate-200" },
    { text: ">", className: "text-cyan-400" },
    { text: " ", className: "text-slate-200" },
    { text: "150", className: "text-amber-400" },
    { text: ":", className: "text-slate-400" },
    { text: "\n", className: "text-slate-200" },
    { text: "    ", className: "text-slate-200" },
    { text: "buy", className: "text-emerald-400" },
    { text: "(", className: "text-slate-400" },
    { text: '"', className: "text-slate-400" },
    { text: "NVDA", className: "text-sky-300" },
    { text: '"', className: "text-slate-400" },
    { text: ", ", className: "text-slate-400" },
    { text: "100", className: "text-amber-400" },
    { text: ")", className: "text-slate-400" },
    { text: "\n", className: "text-slate-200" },
    { text: "    ", className: "text-slate-200" },
    { text: "log", className: "text-emerald-400" },
    { text: "(", className: "text-slate-400" },
    { text: '"', className: "text-slate-400" },
    { text: "Filled at", className: "text-sky-300" },
    { text: '"', className: "text-slate-400" },
    { text: ", ", className: "text-slate-400" },
    { text: "price", className: "text-emerald-400" },
    { text: "(", className: "text-slate-400" },
    { text: '"', className: "text-slate-400" },
    { text: "NVDA", className: "text-sky-300" },
    { text: '"', className: "text-slate-400" },
    { text: "))", className: "text-slate-400" },
    { text: "\n", className: "text-slate-200" },
    { text: "\n", className: "text-slate-200" },
    { text: "for", className: "text-violet-400" },
    { text: " ", className: "text-slate-200" },
    { text: "i", className: "text-slate-200" },
    { text: " ", className: "text-slate-200" },
    { text: "in", className: "text-violet-400" },
    { text: " ", className: "text-slate-200" },
    { text: "range", className: "text-emerald-400" },
    { text: "(", className: "text-slate-400" },
    { text: "3", className: "text-amber-400" },
    { text: ")", className: "text-slate-400" },
    { text: ":", className: "text-slate-400" },
    { text: "\n", className: "text-slate-200" },
    { text: "    ", className: "text-slate-200" },
    { text: "if", className: "text-violet-400" },
    { text: " ", className: "text-slate-200" },
    { text: "cash", className: "text-emerald-400" },
    { text: "()", className: "text-slate-400" },
    { text: " ", className: "text-slate-200" },
    { text: ">", className: "text-cyan-400" },
    { text: " ", className: "text-slate-200" },
    { text: "100", className: "text-amber-400" },
    { text: ":", className: "text-slate-400" },
    { text: "\n", className: "text-slate-200" },
];
