import type { SyntaxToken } from "./components/ui/syntax-typing-animation";

/** IDE-style tokens for the main page typing demo (Python-ish + JSX-ish). */
export const mainDemoSyntaxSegments: SyntaxToken[] = [
    { text: "// Typing in your trade", className: "text-slate-500 italic" },
    { text: "\n", className: "text-slate-200" },
    { text: "if", className: "text-violet-400" },
    { text: " ", className: "text-slate-200" },
    { text: "NVDA", className: "text-sky-300" },
    { text: " ", className: "text-slate-200" },
    { text: "price", className: "text-slate-200" },
    { text: " ", className: "text-slate-200" },
    { text: "<", className: "text-cyan-400" },
    { text: " ", className: "text-slate-200" },
    { text: "180", className: "text-amber-400" },
    { text: ":", className: "text-slate-400" },
    { text: "\n", className: "text-slate-200" },
    { text: " ", className: "text-slate-200" },
    { text: "{", className: "text-slate-400" },
    { text: " ", className: "text-slate-200" },
    { text: "\n", className: "text-slate-200" },
    { text: "    ", className: "text-slate-200" },
    { text: "buy", className: "text-emerald-400" },
    { text: " ", className: "text-slate-200" },
    { text: "15", className: "text-amber-400" },
    { text: " ", className: "text-slate-200" },
    { text: "NVDA", className: "text-sky-300" },
    { text: "\n", className: "text-slate-200" },
    { text: " ", className: "text-slate-200" },
    { text: "}", className: "text-slate-400" },
    { text: " ", className: "text-slate-200" },
    { text: "\n", className: "text-slate-200" },
    { text: "\n", className: "text-slate-200" },
    { text: "if", className: "text-violet-400" },
    { text: " ", className: "text-slate-200" },
    { text: "AMZN", className: "text-sky-300" },
    { text: " ", className: "text-slate-200" },
    { text: "growth", className: "text-slate-200" },
    { text: " ", className: "text-slate-200" },
    { text: "<", className: "text-cyan-400" },
    { text: " ", className: "text-slate-200" },
    { text: "0.1", className: "text-amber-400" },
    { text: " ", className: "text-slate-200" },
    { text: "and", className: "text-violet-400" },
    { text: " ", className: "text-slate-200" },
    { text: "AMZN", className: "text-sky-300" },
    { text: " ", className: "text-slate-200" },
    { text: "price", className: "text-slate-200" },
    { text: " ", className: "text-slate-200" },
    { text: ">", className: "text-cyan-400" },
    { text: " ", className: "text-slate-200" },
    { text: "180", className: "text-amber-400" },
    { text: ":", className: "text-slate-400" },
    { text: "\n", className: "text-slate-200" },
    { text: "{", className: "text-slate-400" },
    { text: "\n", className: "text-slate-200" },
    { text: "    ", className: "text-slate-200" },
    { text: "sell", className: "text-emerald-400" },
    { text: " ", className: "text-slate-200" },
    { text: "10", className: "text-amber-400" },
    { text: " ", className: "text-slate-200" },
    { text: "AMZN", className: "text-sky-300" },
    { text: "\n", className: "text-slate-200" },
    { text: "}", className: "text-slate-400" },
    { text: "\n", className: "text-slate-200" },
    { text: "            ", className: "text-slate-200" },
    { text: "transition", className: "text-rose-400" },
    { text: "\n", className: "text-slate-200" },
    { text: "={{ ", className: "text-slate-400" },
    { text: "\n", className: "text-slate-200" },
    { text: "ease", className: "text-sky-400" },
    { text: ":", className: "text-slate-400" },
    { text: "\n", className: "text-slate-200" },
    { text: ' "', className: "text-slate-400" },
    { text: "easeOut", className: "text-emerald-400" },
    { text: '"', className: "text-slate-400" },
    { text: "\n", className: "text-slate-200" },
    { text: " ", className: "text-slate-200" },
    { text: "}}", className: "text-slate-400" },
    { text: "\n", className: "text-slate-200" },
    { text: "            ", className: "text-slate-200" },
    { text: "animate", className: "text-rose-400" },
    { text: "\n", className: "text-slate-200" },
    { text: "={{ ", className: "text-slate-400" },
    { text: "\n", className: "text-slate-200" },
    { text: "rotate", className: "text-sky-400" },
    { text: ":", className: "text-slate-400" },
    { text: "\n", className: "text-slate-200" },
    { text: " 360", className: "text-amber-400" },
    { text: "\n", className: "text-slate-200" },
    { text: " ", className: "text-slate-200" },
    { text: "}}", className: "text-slate-400" },
    { text: "\n", className: "text-slate-200" },
    { text: "        ", className: "text-slate-200" },
    { text: "/>", className: "text-slate-400" },
    { text: "\n", className: "text-slate-200" },
    { text: "    ", className: "text-slate-200" },
    { text: ");", className: "text-slate-400" },
    { text: "\n", className: "text-slate-200" },
    { text: "}", className: "text-slate-400" },
];
